"""Configuration and constants for parser-shadai."""

from .constants import (
    CACHE_DEFAULT_TTL_SECONDS,
    CHUNK_MAX_CONCURRENT,
    CHUNK_OVERLAP_SIZE_DEFAULT,
    CHUNK_SIZE_DEFAULT,
    CHUNK_SIZE_MIN,
    DEFAULT_LANGUAGE,
    DOCUMENT_TYPE_SAMPLE_SIZE,
    IMAGE_CONSECUTIVE_FAILURE_THRESHOLD,
    LANGUAGE_DETECTION_SAMPLE_SIZE,
    LANGUAGE_SAMPLE_SIZE,
    MAX_RETRIES,
    MIN_EXTRACTED_TEXT_LENGTH,
    OCR_DEFAULT_DPI,
    RETRY_BACKOFF_MULTIPLIER,
    SUPPORTED_LANGUAGES,
    TEMPERATURE_DEFAULT,
)

__all__ = [
    # Text sampling
    "LANGUAGE_DETECTION_SAMPLE_SIZE",
    "LANGUAGE_SAMPLE_SIZE",
    "DOCUMENT_TYPE_SAMPLE_SIZE",
    # Chunking
    "CHUNK_SIZE_DEFAULT",
    "CHUNK_SIZE_MIN",
    "CHUNK_OVERLAP_SIZE_DEFAULT",
    "CHUNK_MAX_CONCURRENT",
    # Validation
    "MIN_EXTRACTED_TEXT_LENGTH",
    # Retry configuration
    "MAX_RETRIES",
    "RETRY_BACKOFF_MULTIPLIER",
    # LLM configuration
    "TEMPERATURE_DEFAULT",
    "DEFAULT_LANGUAGE",
    "SUPPORTED_LANGUAGES",
    # OCR configuration
    "OCR_DEFAULT_DPI",
    # Cache configuration
    "CACHE_DEFAULT_TTL_SECONDS",
    # Image processing
    "IMAGE_CONSECUTIVE_FAILURE_THRESHOLD",
]
